apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deploy
  labels:
    app: hi-py
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hi-py
  template:
    metadata:
      labels:
        app: hi-py
    spec:
      containers:
      - name: hi-py
        image: facuxfdz/hi-python:latest